### ISSUE TITLE
Season 43 day 23 discrepancy

### ISSUE THREAD

**Issue by BMarkham06** [doehm/survivoR#22]
Hi there, just noticed a small discrepancy I wanted to point out:

The tribe_mapping document shows Day 23 of Season 43 as occurring in episode 13, along with days 25 and 26. In the vote_history document, the tribal council from episode 12 of season 43 is listed as occurring on day 23.

Looking at the episodes in question, it looks like Days 22 (captioned at 4:17) and Day 23 (captioned at 17:48) occur in Episode 12, whereas days 24, 25, and 26 occur in Episode 13. 

I believe there needs to be a correction here, with the 5 rows in the tribe_mapping document currently listed as for season 43, episode 13, day 23 changed to season 43, episode 13, day 24.

Thanks again for maintaining this dataset!

**Comment by doehm** [comment]
Hey, thanks again. `day` is now corrected on `tribe_mapping`.

The discrepancy affected episodes 11-13. 

```
tribe_mapping |> 
filter(
  version_season == "US43", 
  episode >= 11
) |> 
distinct(episode, day)

# A tibble: 5 × 2
  episode   day
    <dbl> <dbl>
1      11    21
2      12    23
3      13    24
4      13    25
5      13    26
```

Just a heads up, I plan to update the pipeline to better capture the day variable which should catch any more of these errors if they exist. 

Often I don't pick up on misalignment with `day` since I don't usually use it for analysis, so thanks for letting me know!
