### ISSUE TITLE
Add a castaway_id field to distinguish players who played more than once under different names.

### ISSUE THREAD

**Issue by holtskinner** [doehm/survivoR#6]
Several Players such as Candace, Jonny Fairplay, Amber, and Kim played under different names in different seasons.

I think it makes sense to solve this by using an id field for every player to have throughout every time they play.

I managed to get this CSV together with this data inputted, but I'm not super familiar with R. (I used a python library to extract the csv)

[survivoR Castaways.csv](https://docs.google.com/spreadsheets/d/1T0ys68ur_6mIyGhAjhaAablqRk43a_L4lB6PiIHriLU/edit?usp=sharing)

Also, entirely optional, but I think it would be easier to understand if the "castaway" column specified that it was the nickname/screen name for that player. I changed the column name in this one, and I added some in such as Boston Rob, but this might not always make sense to use, so feel free to do what works best with it.

**Comment by doehm** [comment]
Hi - thanks for your suggestion. This is something I intend to clean up. Ideally, the castaway field is unique across seasons rather than just unique within a season. An ID would fix this but I think a better solution would be to ensure full_name is the unique key, just to limit the number of fields.

Originally I did have the nickname of the castaway but it was fairly inconsistent across data sets. It was easier to ignore it at first and develop the data sets. 

Thanks for putting in the time to refine it, I'll use this to update the field. Definitely makes sense for Boston Rob at least.

**Comment by holtskinner** [comment]
Yeah, I do agree that it would be simpler for `full_name` to be a unique key, but the data wouldn't be entirely accurate.

For example, Kim Spradlin played twice, but her legal name changed between her games.

The first time, she went by "Kim Spradlin" and the second time, she went by "Kim Spradlin-Wolfe" 
Just to keep this data intact for each distinct season, that's why I thought to create the `id` field. I'm just not sure of another more efficient way to list their proper names and keep track of them across seasons.

But, this is your dataset so feel free to treat it however makes the most sense for your use case.

**Comment by holtskinner** [comment]
If you're curious, I came across this when trying to figure out the most common first name of survivor contestants. But it kept getting thrown off by people who played multiple times under different names and by people with the same legal first name, but different common names (E.g. Rob or Bob for Robert) 
Joe/Joseph was the most common name, btw.

**Comment by doehm** [comment]
On review, it was difficult to keep a consistent key using the name fields on their own. While I was keen to keep the datasets as slim as possible, I do think having the ID is the cleanest way to link people across seasons.

I've added the ID to all datasets that have castaway names and referenced the ID appropriately e.g. <code>vote_history</code> now has <code>castwaway_id</code>, <code>vote_id</code> and <code>voted_out_id</code> since those fields reference castaways.

I also used your refined common castaway name field. Boston Rob is Boston Rob.

Should be on CRAN in a couple of days.

Thanks for pulling the ID together. I've listed you as a contributor in the notes :)
