### ISSUE TITLE
Data issues found

### ISSUE THREAD

**Issue by celevitz** [doehm/survivoR#7]
Hi! As I was using the data, I found some data issues. I made some edits to the data -- but realized maybe you would want to know these changes too! I documented my changes in the tab labeled "data cleaning." It's from the Excel data that I downloaded on 10/30/21.

Additionally, I started collecting weather data; it's in the tab "Weather" - but only Seasons 20 and 33 have been added. I'm not sure that it's going to be worth it, given that in a lot of places, there are microclimates that aren't necessarily reflected in a geographical area's broader weather patterns.

I am SO EXCITED that you have pulled these data together. Thank you so much for your work on it!
-Carly

[survivoR_edited_from_download_2021-10-30.xlsx](https://github.com/doehm/survivoR/files/7565620/survivoR_edited_from_download_2021-10-30.xlsx)
nd

**Comment by doehm** [comment]
Hey, thanks for providing the edits! Since the game changes from season to season it is hard to keep consistent definitions, particularly when compiling from multiple sources. Just have to fix them once they're found.

I've got a few changes to make so I'll incorporate these and upload a new xlsx. I can't guarantee I'll make the changes exactly as you've listed but I'll make sure it's accurate.

Thanks for pulling the weather data together, I know how time-consuming it can be! I'm happy to include it. If you manage to complete it I'll pull it into the package. It doesn't make if it's not 100% but would like it to be at least 90-95% complete. Having said that 100% is desirable! 

I'll let you know when I've uploaded the new file.

Dan

**Comment by celevitz** [comment]
Awesome! Yeah, very glad to provide edits as I play around with your and the contributors' data, and I appreciate your receptivity to them.

-Carly

**Comment by doehm** [comment]
Hi Carly, just letting you know that I have updated the data with your edits. I didn't apply them all as some of the odd data items you found are legit records. The data should be more consistent now. 

In summary
- The castaway names are consistent across data sets
- Tribe mapping is updated filling in missing tribe status and Bobby Jon
- Incorrect records from vote history removed.
- Challenge data validated. Many of these were correct since the day spanned multiple episodes. Usually occurred with a quit r medical evac.

The updated data can be downloaded [here](https://gradientdescending.com/survivor/survivoR.xlsx) as well as git

There are a few more things you mentioned that I will look into so will keep the ticket open for the moment.

Thanks,
Dan

**Comment by celevitz** [comment]
Hey Dan, this is fantastic. I look forward to reviewing the updated data. 
I've put the data into Tableau as I currently had it - and I'll need to update it with this round of your updates. Feel free to check it out: https://public.tableau.com/app/profile/carly.levitz

**Comment by doehm** [comment]
Hey Carly, your dashboard looks great! I'll keep it bookmarked and jump in every now and then to see how it's going.

It's useful to see your use case for the data., particularly viewing the castaways across seasons. As you pointed out for example Samoa there is Russell H. and Russell S. for their other seasons they are just Russell. I tried to keep it like this so that it is more consistent with other data sources that may exist so it would be easier to scrape and clean. But this means `castaway` isn't a primary key, but `castaway_id` is. For your case (and probably others), it makes sense for `castaway` to be consistent so it can be used for the label.

I have kept nicknames consistent, it's mostly when there are multiple Russell's, Rob's, Kelly's, Laura's, etc. I could just use the longer version although on the off chance there is another Russell S. (e.g. Smith) we're in the situation. Also, there would be castaways with the same name across seasons, just not in the same season e.g. John, in fact, there would be multiple John C's.

I'll give it some thought. A separate unique name mapping would probably be the easiest solution. For full name, just taking the max `season` grouped by `castaway_id` would be best.

**Comment by celevitz** [comment]
Hi Dan! To be transparent about the changes that I'm making, I started my own repository (or project? I'm verrrrrry new to github and am not totally sure the best way to use it!) to document the changes I make for my own use (Stata code). I wasn't sure if I should have "forked" from your page instead?? https://github.com/celevitz/survivorcbs The following is captured in my code, but I think might be underlying data problems. (I'm also very open to being told I'm wrong or that my interpretation of the data is too narrow!)

1. There's still some messiness in the Vote History data, particularly around double eliminations and double tribal councils. 
- Palau Season 10, Day 12, Episode 5: the vote for Angie is in here twice. The "Order" is both 7 and 8 - drop 8
- Palau Season 10, Day 12, Episode 5: the vote for Willard is in here twice. The "Order" is both 7 and 8 - drop 7
- Season 39 Episode 9 Day 27: there are duplicates where Aaron and Missy are both listed as both Order 10 and Order 11. Drop Order 11 & Aaron; drop Order 10 & Missy
- Season 11 - both Brian and Margaret are listed as both Order 6 and Order 7; drop Brian Order 7 and Margaret Order 6
- Season 13: day 15, both Cao Boi & Cristina are listed as both order 6 and order 7; drop Cao Boi Order 6 and Cristina Order 7
- Gabon Season 17, Episode 6, Day 21: Both Ace & Dan are listed as both Order 7 & 8. Drop Ace Order 8 and Dan Order 7
- Heroes vs Villains, Season 20, Episode 6, Day 15: Both James and Tyson are listed as both order 6 & 7. Drop James Order 7 and Tyson Order 6.
- Nicaragua Season 21, Day 15, Episode 6: the vote is in here twice, as "Order" 6 and 7. Drop Kelly B order 7, and Yve order 6.
- Season 40 - Both Sandra & Parvati are listed as both order 7 & 8. Drop Sandra Order 8, and Parvati Order 7.

2. Additionally in the Vote History data, the votes against Kelley Wentworth in Season 31, Day 36 should have Nullified as True.

3. Some of the Confessional data seem incredibly high to me, given other data I've seen. I haven't cross-checked these data fully with the other data source I've looked at, but it is possible that there are different definitions of what counts as a "confessional" across data sources. For the confessionals that were listed in survivoR as more than 20, I looked at the other data source and am using those numbers instead:
https://docs.google.com/spreadsheets/d/19Xnrs7X0oXsfvnult1cxU-9AD4vWlB44BBcFE_-8FUA/edit#gid=1811461772
- Heidi Season 6 Episode 4 - should be 5 confessionals, not 58. 
- Lillian in Season 7 Episode 12 - listed as 22, should be 13. 
- Eliza Season 9 Episode 3 - should be 3 confessionals, not 36. 
- Ozzy Season 23 Episode 1 - should be 9 confessionals, not 27. 
- Ozzy Season 23 Episode 14 - should be 0 confessionals, not 21. 
- Wes Season 29 Episode 7 - should be 2, not 52. 
- Others that are greater than 20, that give me pause.  Don't have data to disprove this: Rick in Season 38 Episode 14 - listed as 24. And Chris Season 38 Episode 14  - listed as 26. 

-Carly

**Comment by doehm** [comment]
Hi Carly, 

I'm not too surprised there are still issues with the data. It's very difficult to scrape from multiple sources cleanly. Thank you for finding them though. I'll share a Google sheets so you can edit directly.

I used a different source for the confessional data. In some instances double episodes are 2 columns, sometimes 1. It's possible some confessionals were double counted, also possible this episode listing doesn't match other sources or profile interpreted confessionals differently. Heidi and Wes look like clear errors though. I'll cross reference with this source and update. 

Dan

**Comment by doehm** [comment]
Hi Carly,

Just an update, I have updated the data with your notes at the same location. 

The main issues with the confessional:
- The high counts were due to bad scrape / merge. My bad sorry! Only a few of these though. Highest count is now 17 and they check out.
- I cross-checked multiple sources and about 10% are different. Mostly only be a few. The count is largely dependent on the individual that recorded it. There's no authoritative source for this information, no reason why we should believe one source over another, which is one of the reasons why I wanted to create this data package. In the meantime where the data in your link exists and there is a good match to the castaway I have used that value, otherwise used the value that exists. The only other way is to probably text mine episode transcripts!
- The source I used didn't account for recap episodes so there was misalignment. This has been corrected.

Vote history:
- I have made the edits that you have suggested and will be doing a bit of deep dive pick up anymore. 

I expect there are going to be issues with the challenge data set as well. It's very difficult to capture that info automatically. I would like to 
- complete the challenge name field
- add a challenge id to identify immunity and reward challenges
- identify the winners of individual reward and those that were selected for the reward. It gets very messy when someone wins and hands the reward to someone else.

I have pulled the data into a google sheets. Would you be comfortable sharing your email so I can share it with you?

Dan

**Comment by ben-tanen** [comment]
Hey! I noticed an issue with the data (it seems like Bobby Jon Drinkard is missing from the tribe mapping data for S10 + 11) that was raised previously in this issue. @doehm noted fixing the issue (see [here](https://github.com/doehm/survivoR/issues/7#issuecomment-9)), but as of 03/10/2022, the data set that is referenced in that comment still seems to be missing a fix for Bobby Jon in the tribe mapping tab/data. I'm also seeing the same issue in the data pulled directly from the R library.

![Screen Shot 2022-03-10 at 5 40 19 PM](https://user-images.githubusercontent.com/6319890/157779450-04489d41-fe5e-4308-92d3-0a2395865a84.png)

No rush to fix, just wanted to flag it!

Also wanted to say thank you so much for putting together this data! I know it's a somewhat thankless job, so just wanted to say how much I appreciate it!

**Comment by doehm** [comment]
Hey Ben, thanks for letting me know about this issue. Looks like the fix was reverted in a more recent update. Sorry about that. 

I have corrected those records on the tribe mapping and just pushed an update to Git so `devtools::install_github("doehm/survivoR)` should give you the most up-to-date data. I'll make a release to CRAN in a few weeks with more updates. Hopefully, finally v1.0.

Thank you for your comments! It's good to know that others are appreciative of the work that has gone into this package. And I couldn't have done it without the help of @celevitz.

Please let me know if there are any more issues.

**Comment by ryanmberry** [comment]
Hey there - thank you for this data set! I've never used R before, and this has been a fun thing to muck around with! I've found a handful of data errors in vote_history that I'd like to share with you.

1. US08, order 7: Kathy is listed as having voted for "Kidnap". Her vote should probably be NA, and her vote_event should be "Kidnap"
2. US09, order 3 and 4: All votes that should have been order 3 (John P's elimination) are stored as order 4. These need to be separated from the real order 4 votes.
3.  US10, order 7: All votes here (Willard's elimination) are stored with vote_order 2, when they should be vote_order 1.
4. US13, order 7: Similar to Kathy above, Nate's vote is also stored as "Kidnap". Additionally, Nate 's immunity == "Individual" instead of "NA". (You should check Rupert/Kathy/Nate kidnappings for consistency. Rupert was in US07 order 4.)
5. US21, order 2: All votes here (Yve's elimination) are stored with vote_order 2, when they should be vote_order 1.
6. US24, order 3 and 4: Matt's vote for Colton is stores as order 4 instead of order 3.
7. US31 order 15 and US42 order 4: These votes were consensus votes (Kimmi and Jenny). Jenny's consensus vote is given its own vote_order while Kimmi's is not. There should be consistency here.
8. US41, order 11: Shan and Liana's NA votes on the revote are stored as vote_order 1, when they should be vote_order 2.
9. US42, order 11: Rocksroy has a vote against Hai. This vote shouldn't exist in the data set, since Rocksroy was no longer in the game.
10. US43, order 7: Dwight has a vote against Jeanine. This vote shouldn't exist in the data set, since Dwight was no longer in the game.
11. From US35 onward, whenever there is a firemaking challenge, all players remaining in the game have NA votes. Before that point, whenever there was a firemaking challenge, only the players participating in the challenge have NA votes. There might be intent behind this, but calling it out in case you want to revisit for consistency.

I looked quickly at some AU data too, and saw that non-eliminating votes had order == NA. I don't think I agree with this choice - I'd rather see them have an actual numerical value.

One nitpick - season_summary has a column named "viewers_premier". This should instead be named "viewers_premiere".

Thank you! This data set is awesome and I'm excited to keep playing with it.

**Comment by doehm** [comment]
Hi Ryan,

Thanks for sending them through. Very much appreciated. I have now made the edits. Install from Github to get the chanages. A couple of things to note:

- I have updated the kidnaps to 'kidnapped' in vote_event and added 'removed_from_tribal' to immunity to indicate they were immune from the vote
- On point 7 I have added in the Kimmi votes for US31 for consistency.
- On point 11 I have kept this consistent for 35 onwards for the F4 fire challenge since it's a slightly different case. The vote is to keep someone safe rather than to vote them out. I have contemplated moving this to the challenge_results data set but kept it on vote_history for the time being
- On AU, AU is really annoying for the data! The non-elimination votes are there for recording the event even though it wasn't a voted out. In some cases, not all, the castaways were under the impression they were voting someone out. This is an important data point. Sometimes they knew they were voting for a different reason. I have thought about removing these from vote_history and storing them elsewhere, but for now, have kept them there. I want to leave it up to the user to use them as they see fit and it's fairly easy to filter them out. Otherwise open to ideas. My priority is to make sure the data is easy to use. Some of the AU seasons need a rewatch to work it out but I really don't have time for that!
- Changed to viewers_premiere. Please nitpick! I want this to be dialled!

I'll mark this issue off as closed. If there are any more please open a new issue

Cheers,
Dan
